http://localhost:8080/api/features

###
http://localhost:8080/api/instances/All
###
http://localhost:8080/api/components/All

###
http://localhost:8080/api/version

###
http://localhost:8080/api/scopes

###
http://localhost:8080/api/platform

###
http://localhost:8080/api/controlplanestatus